[package]
name = "outref"
version = "0.5.1"
edition = "2021"
description = "Out reference"
license = "MIT"
repository = "https://github.com/Nugine/rust-utils"
keywords = ["write-only", "reference", "slice"]
categories = ["no-std", "rust-patterns"]
rust-version = "1.63.0"
